---
- name: "Ensure terminfo packages are present"
  apt:
    name: "{{ shell_tweaks_packages_terminfo }}"
    state: "present"
  when: "ansible_facts['pkg_mgr'] == 'apt'"

- name: "Ensure terminfo packages are present"
  package:
    name: "{{ shell_tweaks_packages_terminfo }}"
    state: "present"
  when: "ansible_facts['pkg_mgr'] != 'apt'"
