---
- name: "Set /etc/hostname to FQDN of the server"
  copy:
    dest: "/etc/hostname"
    owner: "root"
    group: "root"
    mode: "0644"
    content: |
      {{ hostname_fqdn }}
  tags: ["deploy", "deploy-hostname"]
  notify: "set-hostname"

- name: "Ensure /etc/hosts contains all hostnames and aliases of the server"
  blockinfile:
    dest: "/etc/hosts"
    owner: "root"
    group: "root"
    mode: "0644"
    content: |
      {% for host in hostname_hosts %}
      {{ host.ip }}	{{ host.fqdn }}		{{ host.alias | default([]) | join(" ") }}
      {% endfor %}
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
  tags: ["deploy", "deploy-hostname"]
