---
namespace: "famedly"
name: "base"
version: "0.2.0"
readme: "README.md"
authors:
  - "Evelyn Alicke <e.alicke@famedly.com>"
  - "Jadyn Emma Jäger <jadyn@jadyn.dev>"
  - "Jan Christian Grünhage <jan.christian@gruenhage.xyz>"
  - "Johanna Dorothea Reichmann <transcaffeine@finallycoffee.eu>"
  - "Lars Kaiser <l.kaiser@famedly.com>"
  - "Lukas Lihotzki <l.lihotzki@famedly.com>"
  - "Vincent Wilke"
description: "Common functionality needed on hosts to build complex services on."
license: ["AGPL-3.0-only"]
build_ignore: ["*.tar.gz"]
repository: "https://github.com/famedly/ansible-collection-base"
issues: "https://github.com/famedly/ansible-collection-base/issues"
