---
- name: "Ensure sudo is installed"
  package:
    name: "sudo"
    state: "present"
  register: "task_result"
  until: "task_result is success"
  retries: 3
  delay: 2
  tags: ['prepare', 'prepare-users']

- name: "Query groups available on server"
  ansible.builtin.getent:
    database: "group"
  tags: ['deploy', 'deploy-users']

- name: "Loop over users and include per-user tasks"
  include_tasks: "user.yml"
  loop: "{{ users | dict2items(key_name='name', value_name='attrs') }}"
  loop_control:
    loop_var: "user"
    label: "{{ user.name }}"
  tags: ['deploy', 'deploy-users']

- name: "Template sudoers.d managed file"
  template:
    src: "sudoers.j2"
    dest: "/etc/sudoers.d/{{ users_sudo_namespace }}"
    owner: "root"
    mode: "0440"
    validate: "/usr/sbin/visudo -cf %s"
  become: true
  tags: ['deploy', 'deploy-users']
