- name: "create user {{ user.name }}"
  user:
    name: "{{ user.name }}"
    shell: "{{ user_set_shell | default(true) | ternary(user.shell | default('/bin/bash'), omit) }}"
    groups: "{{ user_set_groups | default(true) | ternary(user.groups | default([]), omit) }}"
    comment: "{{ user_set_gecos | default(true) | ternary(user.gecos | default(omit), omit) }}"
  become: yes

- name: "add ssh key for {{ user.name }}"
  authorized_key:
    user: "{{ user.name }}"
    key: "{{ key.key }}"
    state: "{{ 'present' if key.active else 'absent' }}"
  become: yes
  loop: "{{ user.ssh }}"
  loop_control:
    loop_var: key
