---
- name: "Ensure user {{ user.name }} is {{ user.attrs.active | default(false) | ternary('present', 'absent') }}"
  user:
    name: "{{ user.name }}"
    shell: "{{ user.attrs.shell | default(omit) }}"
    groups: >-
      {{
        omit
        if user.attrs.groups is not sequence
        else ansible_facts.getent_group | intersect(user.attrs.groups)
      }}
    append: "{{ user.attrs.append | default(omit) }}"
    comment: "{{ user.attrs.gecos | default(omit) }}"
    password: "{{ user.attrs.password | default(omit) }}"
    password_lock: "{{ user.attrs.password_lock | default(omit) }}"
    uid: "{{ user.attrs.uid | default(omit) }}"
    state: "{{ user.attrs.active | default(false) | ternary('present', 'absent') }}"
    remove: true
  become: true

- name: "Ensure ssh keys for {{ user.name }} are up to date"
  authorized_key:
    user: "{{ user.name }}"
    key: "{{ user.attrs.ssh | join('\n') }}"
    exclusive: true
  become: true
  when: "user.attrs.active | default(false)"
  ignore_errors: "{{ ansible_check_mode }}"
