---
- name: "Ensure user {{ user.name }} is {{ user.attrs.active | default(false) | ternary('present', 'absent') }}"
  user:
    name: "{{ user.name }}"
    shell: "{{ user.attrs.shell | default(omit) }}"
    groups: "{{ user.attrs.groups | default([]) }}"
    comment: "{{ user.attrs.gecos | default(omit) }}"
    password: "{{ user.attrs.password | default(omit) }}"
    uid: "{{ user.attrs.uid | default(omit) }}"
    state: "{{ user.attrs.active | default(false) | ternary('present', 'absent') }}"
  become: true

- name: "Ensure ssh keys for {{ user.name }} are up to date"
  authorized_key:
    user: "{{ user.name }}"
    key: "{{ user.attrs.ssh | join('\n') }}"
    exclusive: true
  become: true
  when: user.attrs.active | default(false)
