---
- name: "Ensure Pip is installed."
  package:
    name: "{{ pip_package_name }}"
    state: "present"

- name: "Install packages from list"
  pip:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default(omit) }}"
    virtualenv: "{{ item.virtualenv | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    executable: "{{ pip_executable }}"
    extra_args: "{{ pip_executable_extra_args | default(omit) }}"
  loop: "{{ pip_packages }}"
  environment: "{{ pip_environment_variables }}"

- name: "Install packages from requirements file"
  pip:
    requirements: "{{ pip_requirements_file }}"
    virtualenv: "{{ pip_package_virtualenv | default(omit) }}"
    state: "{{ pip_package_state | default(omit) }}"
    executable: "{{ pip_executable }}"
    extra_args: "{{ pip_executable_extra_args | default(omit) }}"
  when: "pip_requirements_file"
  environment: "{{ pip_environment_variables }}"
