---
- name: "Reload sshd using systemd"
  ansible.builtin.systemd:
    name: "sshd"
    state: "reloaded"
  when: "ansible_service_mgr == 'systemd'"
  listen: "reload sshd"

- name: "Reload sshd using runit"
  community.general.runit:
    name: "sshd"
    state: "reloaded"
  when: "ansible_service_mgr == 'runit'"
  listen: "reload sshd"

- name: "Restart sshd using dinit"
  ansible.builtin.command:
    argv:
      - dinitctl
      - --system
      - restart
      - sshd
  when: ansible_os_family in ["Chimera"]
  listen: "reload sshd"
