---
  - name: Add opendkim user
    ansible.builtin.user:
      name: "{{ opendkim_user_name }}"
      group: "{{ email_group_name }}"

  - name: create directory for opendkim config and dkim-certs
    file:
      path: '{{ opendkim_base_path }}/{{ item }}'
      state: directory
      owner: "{{ opendkim_user_name }}"
      group: "{{ email_group_name }}"
    with_items:
      - 
      - certs
#      - opendkim/config

#  - name: configure opendkim
#    template:
#      src: "opendkim/{{ item }}"
#      dest: "{{ opendkim_base_path }}/config/{{ item }}"
#      owner: root #TODO do not run as root
#      group: root
#      mode: '0744'
#    with_items:
#      - dkim_signing.conf

  - name: opendkim cert-gen
    import_tasks: opendkim_cert_gen.yml

  - name: install opendkim container
    docker_container:
      name: "{{ opendkim_docker_name }}"
      hostname: "{{ opendkim_docker_name }}"
      image: "{{ opendkim_docker_image }}"
      ports: "{{ opendkim_docker_ports }}"
      labels: "{{ opendkim_docker_labels }}"
      restart_policy: unless-stopped
      recreate: true
      pull: true
      command: "/usr/sbin/opendkim -f -l -p SOCKETSPEC -d {{ email_domain }} -k {{ opendkim_cert_path }}/{{ opendkim_cert_filename }} -s {{ opendkim_selector_name }}"
      volumes:
        - "{{ opendkim_base_path }}/certs/{{ opendkim_cert_filename }}:{{ opendkim_cert_path }}/{{ opendkim_cert_filename }}"
