---
  - name: Add opendkim group
    ansible.builtin.group:
      name: "{{ opendkim_group_name }}"
      state: present
 
  - name: Add opendkim user
    ansible.builtin.user:
      name: "{{ opendkim_user_name }}"
      group: "{{ opendkim_group_name }}"
    register: opendkim_user

  - name: create directory for opendkim config and dkim-certs
    file:
      path: '{{ opendkim_base_path }}/{{ item }}'
      state: directory
      owner: "{{ opendkim_user.name }}"
      group: "{{ opendkim_user.group }}"
      mode: '0700'
    with_items:
      - 
      - certs
      - config
      - certs/opendkim

  - name: configure opendkim
    template:
      src: "opendkim/opendkim.conf"
      dest: "{{ opendkim_base_path }}/config/opendkim.conf"
      owner: "{{ opendkim_user.name }}"
      group: "{{ opendkim_user.group }}"
      mode: '0700'

  - name: opendkim cert-gen
    import_tasks: opendkim_cert_gen.yml

  - name: install opendkim container
    docker_container:
      name: "{{ opendkim_docker_name }}"
      hostname: "{{ opendkim_docker_name }}"
      image: "{{ opendkim_docker_image }}"
      ports: "{{ opendkim_docker_ports }}"
      labels: "{{ opendkim_docker_labels }}"
      restart_policy: unless-stopped
      recreate: true
      user: "{{ opendkim_user.uid }}" #:{{ opendkim_user.group }}"
      pull: true
      command: "/usr/sbin/opendkim -x {{ opendkim_conf_path }}"
      #command: "/usr/sbin/opendkim -f -l -p {{ opendkim_listening_socket }} -d {{ email_domain }} -k {{ opendkim_cert_path }}/{{ opendkim_cert_filename }} -s {{ opendkim_selector_name }}"
      volumes:
        - "{{ opendkim_base_path }}/certs/{{ opendkim_cert_filename }}:/{{ opendkim_cert_filename }}"
        - "{{ opendkim_base_path }}/config/opendkim.conf:{{ opendkim_conf_path }}"

  - name: debug
    debug:
      msg: "{{ opendkim_base_path }}/config/opendkim.conf:{{ opendkim_conf_path }}"
