---
# ARE YOU **SURE** YOU WANT TO BUMP THIS VERSION?
redis_version: "7.2.4"
redis_allow_non_foss_yes_really: false

redis_user: "{{ redis_prefix }}redis"
redis_basepath: "/opt/redis"
redis_data_dir: "{{ redis_basepath }}/{{ redis_prefix }}data"
redis_config_dir: "{{ redis_basepath }}/{{ redis_prefix }}config"
redis_config_file: "{{ redis_config_dir }}/redis.conf"
redis_secret: ~

redis_config_bind_ip: "0.0.0.0"
redis_config_unix_socket_path: ~
redis_config_unix_socket_perm: 775
redis_config_max_memory_mb: ~
redis_config_max_memory_policy: ~  # allkeys-lru

# Overwrite per-instance to be able to run many instances on the same host
# prefix should be sth like 'matrix_', modifies mapped directories, container name and uer
redis_prefix: ""
redis_docker_labels: {}
redis_docker_configpath: "/usr/local/etc/redis/redis.conf"

redis_container_image_reference: >-
  {{
    redis_container_image_repository
    + ':'
    + redis_container_image_tag | default(redis_version + '-alpine')
  }}
redis_container_image_repository: >-
  {{
    (
      container_registries[redis_container_image_registry]
      | default(redis_container_image_registry)
    )
    + '/'
    + redis_container_image_namespace | default('')
    + redis_container_image_name
  }}
redis_container_image_registry: "docker.io"
redis_container_image_name: "redis"

redis_container_image_force_pull: "{{ redis_container_image_tag is defined }}"

redis_docker_container_name: "{{ redis_prefix }}redis"
redis_docker_ports: ["6379:6379"]
redis_docker_networks: ~
redis_docker_volumes: ~
