---
galaxy_info:
  author: Jan Christian Grünhage <jan.christian@gruenhage.xyz>
  description: Basic user setup

  min_ansible_version: "2.13"

  galaxy_tags: []
  platforms:
    - name: Debian
      versions:
        - stretch
        - buster
        - bullseye

  license: AGPL-3.0-or-later

dependencies: []
