---
name: ansible-lint
on: [pull_request]
jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ansible_collections/famedly/base
      - name: Run ansible-lint
        uses: famedly/ansible-lint-action@main
        with:
          path: ansible_collections/famedly/base
